### ISSUE TITLE
keep multiline declaration format

### ISSUE THREAD

**Issue by yukulele** [ThisIsManta/stylus-supremacy#35]
I'ts sometime better to keep multiline declaration:
```stylus
input.shadowed
    color black
    background color green
    box-shadow:
        0px 0px 5px black,
        0px 5px 1px 1px blue,
        10px 10px 0px red,
        0px 0px 0px 1px yellow inset
```
stylus-supremacy is actually convert that to:
```stylus
input.shadowed
    color black
    background color green
    box-shadow 0px 0px 5px black, 0px 5px 1px 1px blue, 10px 10px 0px red, 0px 0px 0px 1px yellow inset
```

**Comment by ThisIsManta** [comment]
Thanks for the feedback. I'll work on that soon.

**Comment by ThisIsManta** [comment]
Hello @yukulele,

Sorry to keep you waiting. The version 2.12.0 is out as NPM and VSCode extension. In order to allow such multi-line, you need to set [`preserveNewLinesBetweenPropertyValues`](https://thisismanta.github.io/stylus-supremacy/#option-preserve-new-lines-between-property-values) formatting option to `true` manually.

Cheers!
